#' Bootstrap confidence intervals for layer-specific standardized effects
#'
#' Constructs nonparametric confidence intervals for Hedges' g using the
#' matched, group-stratified subject bootstrap draws generated by
#' `bootstrap_effect_covariance()`. Percentile and basic intervals reuse those
#' bootstrap draws. BCa intervals additionally estimate the acceleration term
#' from leave-one-subject-out jackknife effects within each omic.
#'
#' These intervals are an uncertainty-reporting option. They do not replace the
#' analytic standard errors or p-values used by the current OmicsBraid
#' hypothesis tests unless a future method version explicitly validates such a
#' change.
#'
#' @param effects Output of `estimate_effects()` after any scientifically
#'   justified orientation has been applied.
#' @param bootstrap An `omics_braid_covariance` object containing `boot_effects`.
#' @param method One of `"percentile"`, `"basic"`, or `"bca"`.
#' @param conf_level Confidence level.
#' @param min_boot Minimum number of finite bootstrap draws required per
#'   entity-by-omic effect.
#' @param data Required only for `method = "bca"`; an `omics_braid_data` object
#'   used to calculate leave-one-subject-out jackknife effects.
#' @param group Metadata group column, required for BCa.
#' @param reference Reference-group label, required for BCa.
#' @param comparison Comparison-group label, required for BCa.
#' @param min_n Minimum observations per group used for jackknife effects.
#' @return A data frame with one row per usable entity-by-omic effect and
#'   bootstrap interval diagnostics.
#' @export
bootstrap_effect_intervals <- function(effects, bootstrap,
                                       method = c("percentile", "basic", "bca"),
                                       conf_level = 0.95, min_boot = 100L,
                                       data = NULL, group = NULL,
                                       reference = NULL, comparison = NULL,
                                       min_n = 3L) {
  .validate_effect_table(effects)
  method <- match.arg(method)
  if (!inherits(bootstrap, "omics_braid_covariance") || is.null(bootstrap$boot_effects)) {
    .stopf("'bootstrap' must be an omics_braid_covariance object containing boot_effects.")
  }
  if (!is.numeric(conf_level) || length(conf_level) != 1L || !is.finite(conf_level) ||
      conf_level <= 0 || conf_level >= 1) {
    .stopf("'conf_level' must lie strictly between 0 and 1.")
  }
  if (!is.numeric(min_boot) || length(min_boot) != 1L || !is.finite(min_boot) || min_boot < 20L) {
    .stopf("'min_boot' must be at least 20.")
  }
  alpha <- 1 - conf_level

  jack <- NULL
  if (identical(method, "bca")) {
    if (is.null(data) || is.null(group) || is.null(reference) || is.null(comparison)) {
      .stopf("BCa intervals require 'data', 'group', 'reference', and 'comparison'.")
    }
    validate_omics_braid_data(data)
    jack <- .jackknife_effect_draws(
      data = data, group = group, reference = reference,
      comparison = comparison, effects = effects, min_n = min_n
    )
  }

  rows <- vector("list", nrow(effects))
  k <- 0L
  for (i in seq_len(nrow(effects))) {
    e <- as.character(effects$entity[i])
    o <- as.character(effects$omic[i])
    theta <- effects$effect[i]
    if (!is.finite(theta) || is.null(bootstrap$boot_effects[[o]]) ||
        !e %in% colnames(bootstrap$boot_effects[[o]])) next

    b <- bootstrap$boot_effects[[o]][, e]
    b <- b[is.finite(b)]
    nb <- length(b)
    if (nb < min_boot) next

    q <- .bootstrap_ci_from_draws(
      theta = theta, draws = b, method = method,
      alpha = alpha,
      jackknife = if (!is.null(jack) && !is.null(jack[[o]]) && e %in% colnames(jack[[o]])) jack[[o]][, e] else NULL
    )
    k <- k + 1L
    rows[[k]] <- data.frame(
      entity = e,
      omic = o,
      ci_method = method,
      conf_level = conf_level,
      boot_n = nb,
      boot_mean = mean(b),
      boot_sd = stats::sd(b),
      boot_bias = mean(b) - theta,
      conf_low_boot = q$low,
      conf_high_boot = q$high,
      bca_z0 = q$z0,
      bca_acceleration = q$acceleration,
      bca_prob_low = q$prob_low,
      bca_prob_high = q$prob_high,
      stringsAsFactors = FALSE
    )
  }
  rows <- rows[seq_len(k)]
  if (!length(rows)) {
    return(data.frame(
      entity = character(), omic = character(), ci_method = character(),
      conf_level = numeric(), boot_n = integer(), boot_mean = numeric(),
      boot_sd = numeric(), boot_bias = numeric(), conf_low_boot = numeric(),
      conf_high_boot = numeric(), bca_z0 = numeric(),
      bca_acceleration = numeric(), bca_prob_low = numeric(),
      bca_prob_high = numeric(), stringsAsFactors = FALSE
    ))
  }
  ans <- do.call(rbind, rows)
  rownames(ans) <- NULL
  ans
}

#' Bootstrap confidence intervals for GLS consensus effects
#'
#' Uses matched subject-bootstrap layer-effect draws from
#' `bootstrap_effect_covariance()` and the fitted covariance structure to form a
#' bootstrap distribution of the GLS consensus effect. The hypothesis tests and
#' analytic standard errors remain unchanged; these intervals are intended for
#' robust uncertainty reporting and coverage validation.
#'
#' @param effects Layer-specific effect table.
#' @param bootstrap An `omics_braid_covariance` object.
#' @param integrated Optional output of `integrate_effects()`.
#' @param method `"percentile"` or `"basic"`.
#' @param conf_level Confidence level.
#' @param min_boot Minimum usable bootstrap consensus draws.
#' @param min_omics Minimum finite omic layers required in an individual
#'   bootstrap replicate.
#' @return One row per entity with bootstrap consensus interval diagnostics.
#' @export
bootstrap_consensus_intervals <- function(effects, bootstrap, integrated = NULL,
                                          method = c("percentile", "basic"),
                                          conf_level = 0.95, min_boot = 100L,
                                          min_omics = 2L) {
  .validate_effect_table(effects)
  method <- match.arg(method)
  if (!inherits(bootstrap, "omics_braid_covariance") || is.null(bootstrap$boot_effects)) {
    .stopf("'bootstrap' must be an omics_braid_covariance object containing boot_effects.")
  }
  if (is.null(integrated)) integrated <- integrate_effects(effects, covariance = bootstrap)
  if (!is.numeric(conf_level) || length(conf_level) != 1L || !is.finite(conf_level) ||
      conf_level <= 0 || conf_level >= 1) {
    .stopf("'conf_level' must lie strictly between 0 and 1.")
  }
  if (!is.numeric(min_boot) || length(min_boot) != 1L || min_boot < 20L) .stopf("'min_boot' must be at least 20.")
  alpha <- 1 - conf_level

  rows <- list(); k <- 0L
  for (e in integrated$entity) {
    d <- effects[effects$entity == e & is.finite(effects$effect) & is.finite(effects$se), , drop = FALSE]
    os <- d$omic
    if (length(os) < min_omics) next
    V <- diag(d$se^2, nrow = nrow(d), ncol = nrow(d))
    dimnames(V) <- list(os, os)
    if (!is.null(bootstrap$covariance[[e]])) {
      V0 <- bootstrap$covariance[[e]]
      common <- intersect(os, intersect(rownames(V0), colnames(V0)))
      if (length(common)) V[common, common] <- V0[common, common, drop = FALSE]
    }
    V <- .make_psd(V)

    B <- bootstrap$B %||% max(vapply(bootstrap$boot_effects, nrow, integer(1)))
    theta_b <- rep(NA_real_, B)
    for (b in seq_len(B)) {
      yb <- rep(NA_real_, length(os)); names(yb) <- os
      for (j in seq_along(os)) {
        o <- os[j]
        M <- bootstrap$boot_effects[[o]]
        if (!is.null(M) && e %in% colnames(M) && b <= nrow(M)) yb[j] <- M[b, e]
      }
      keep <- is.finite(yb)
      if (sum(keep) < min_omics) next
      Vk <- V[keep, keep, drop = FALSE]
      Wk <- .safe_inverse(Vk)
      one <- rep(1, sum(keep))
      den <- as.numeric(t(one) %*% Wk %*% one)
      if (!is.finite(den) || den <= 0) next
      wk <- as.numeric(Wk %*% one / den)
      theta_b[b] <- sum(wk * yb[keep])
    }
    theta_b <- theta_b[is.finite(theta_b)]
    if (length(theta_b) < min_boot) next
    theta <- integrated$integrated_effect[match(e, integrated$entity)]
    q <- .bootstrap_ci_from_draws(theta, theta_b, method = method, alpha = alpha)
    k <- k + 1L
    rows[[k]] <- data.frame(
      entity = e,
      ci_method = method,
      conf_level = conf_level,
      boot_n = length(theta_b),
      boot_mean = mean(theta_b),
      boot_sd = stats::sd(theta_b),
      boot_bias = mean(theta_b) - theta,
      conf_low_boot = q$low,
      conf_high_boot = q$high,
      stringsAsFactors = FALSE
    )
  }
  if (!length(rows)) {
    return(data.frame(
      entity = character(), ci_method = character(), conf_level = numeric(),
      boot_n = integer(), boot_mean = numeric(), boot_sd = numeric(),
      boot_bias = numeric(), conf_low_boot = numeric(), conf_high_boot = numeric(),
      stringsAsFactors = FALSE
    ))
  }
  ans <- do.call(rbind, rows)
  rownames(ans) <- NULL
  ans
}

.bootstrap_ci_from_draws <- function(theta, draws, method, alpha, jackknife = NULL) {
  draws <- draws[is.finite(draws)]
  probs <- c(alpha / 2, 1 - alpha / 2)
  if (identical(method, "percentile")) {
    qq <- as.numeric(stats::quantile(draws, probs = probs, names = FALSE, type = 7, na.rm = TRUE))
    return(list(low = qq[1], high = qq[2], z0 = NA_real_, acceleration = NA_real_,
                prob_low = probs[1], prob_high = probs[2]))
  }
  if (identical(method, "basic")) {
    qq <- as.numeric(stats::quantile(draws, probs = rev(probs), names = FALSE, type = 7, na.rm = TRUE))
    return(list(low = 2 * theta - qq[1], high = 2 * theta - qq[2], z0 = NA_real_, acceleration = NA_real_,
                prob_low = probs[1], prob_high = probs[2]))
  }
  if (!identical(method, "bca")) .stopf("Unsupported bootstrap CI method: %s", method)
  if (is.null(jackknife)) return(list(low = NA_real_, high = NA_real_, z0 = NA_real_, acceleration = NA_real_, prob_low = NA_real_, prob_high = NA_real_))
  jackknife <- jackknife[is.finite(jackknife)]
  if (length(jackknife) < 5L) return(list(low = NA_real_, high = NA_real_, z0 = NA_real_, acceleration = NA_real_, prob_low = NA_real_, prob_high = NA_real_))

  prop <- mean(draws < theta)
  # Avoid infinite bias-correction when every bootstrap draw lies on one side.
  eps <- 1 / (2 * length(draws))
  prop <- min(max(prop, eps), 1 - eps)
  z0 <- stats::qnorm(prop)
  jm <- mean(jackknife)
  u <- jm - jackknife
  den <- 6 * (sum(u^2)^(3 / 2))
  acc <- if (is.finite(den) && den > 0) sum(u^3) / den else 0
  za <- stats::qnorm(probs)
  den_adj <- 1 - acc * (z0 + za)
  tiny <- abs(den_adj) < 1e-12
  den_adj[tiny] <- ifelse(den_adj[tiny] < 0, -1e-12, 1e-12)
  adj <- stats::pnorm(z0 + (z0 + za) / den_adj)
  # Numerical protection only; BCa probabilities should remain strictly inside (0,1).
  adj <- pmin(pmax(adj, 1 / (length(draws) + 1)), length(draws) / (length(draws) + 1))
  qq <- as.numeric(stats::quantile(draws, probs = adj, names = FALSE, type = 7, na.rm = TRUE))
  list(low = qq[1], high = qq[2], z0 = z0, acceleration = acc,
       prob_low = adj[1], prob_high = adj[2])
}

.jackknife_effect_draws <- function(data, group, reference, comparison, effects, min_n = 3L) {
  if (!group %in% names(data$metadata)) .stopf("Metadata column '%s' not found.", group)
  ids <- as.character(data$metadata[[data$sample_id]])
  grp_all <- as.character(data$metadata[[group]])
  out <- list()
  for (o in names(data$assays)) {
    ef <- effects[effects$omic == o & is.finite(effects$effect), , drop = FALSE]
    feats <- intersect(ef$entity, rownames(data$assays[[o]]))
    if (!length(feats)) next
    mat <- data$assays[[o]][feats, , drop = FALSE]
    idx <- match(colnames(mat), ids)
    ok <- is.finite(idx) & grp_all[idx] %in% c(reference, comparison)
    mat <- mat[, ok, drop = FALSE]
    grp <- grp_all[idx[ok]]
    ns <- ncol(mat)
    J <- matrix(NA_real_, nrow = ns, ncol = length(feats),
                dimnames = list(colnames(mat), feats))
    for (i in seq_len(ns)) {
      keep <- seq_len(ns) != i
      if (sum(grp[keep] == reference) < min_n || sum(grp[keep] == comparison) < min_n) next
      J[i, ] <- .hedges_g_matrix(mat[, keep, drop = FALSE], grp[keep], reference, comparison, min_n = min_n)
    }
    orient <- attr(effects, "orientation")
    if (!is.null(orient) && o %in% names(orient)) J <- J * orient[o]
    out[[o]] <- J
  }
  out
}

.apply_layer_bootstrap_intervals <- function(effects, intervals, method) {
  if (is.null(intervals) || !nrow(intervals)) return(effects)
  out <- effects
  out$conf_low_analytic <- out$conf_low
  out$conf_high_analytic <- out$conf_high
  key <- paste(out$entity, out$omic, sep = "\r")
  ikey <- paste(intervals$entity, intervals$omic, sep = "\r")
  ii <- match(key, ikey)
  out$conf_low_bootstrap <- intervals$conf_low_boot[ii]
  out$conf_high_bootstrap <- intervals$conf_high_boot[ii]
  out$ci_boot_n <- intervals$boot_n[ii]
  use <- is.finite(out$conf_low_bootstrap) & is.finite(out$conf_high_bootstrap)
  out$conf_low[use] <- out$conf_low_bootstrap[use]
  out$conf_high[use] <- out$conf_high_bootstrap[use]
  out$ci_method <- ifelse(use, method, "analytic_fallback")
  out
}

.apply_consensus_bootstrap_intervals <- function(integrated, intervals, method) {
  if (is.null(intervals) || !nrow(intervals)) return(integrated)
  out <- integrated
  out$conf_low_analytic <- out$conf_low
  out$conf_high_analytic <- out$conf_high
  ii <- match(out$entity, intervals$entity)
  out$conf_low_bootstrap <- intervals$conf_low_boot[ii]
  out$conf_high_bootstrap <- intervals$conf_high_boot[ii]
  out$ci_boot_n <- intervals$boot_n[ii]
  use <- is.finite(out$conf_low_bootstrap) & is.finite(out$conf_high_bootstrap)
  out$conf_low[use] <- out$conf_low_bootstrap[use]
  out$conf_high[use] <- out$conf_high_bootstrap[use]
  out$ci_method <- ifelse(use, method, "analytic_fallback")
  out
}
